Add refresh token expiration time
diem/reference-wallet pull request #70
Opened 2021-03-31 11:56 UTC by martonmaya

2021-03-31 17:31 UTC, yanivmo requested changes

2021-03-31 17:31 UTC, yanivmo commented on backend/tests/webapp_tests/routes/test_user.py
> +    def test_with_valid_password_reset_token_expiration(
Add test for resetting the password twice with the same token.

2021-03-31 17:31 UTC, yanivmo commented on backend/wallet/storage/user.py
> +        user.password_reset_token_expiration = datetime.now() - timedelta(minutes=30)
Do you just want to expire the token? If this is the only purpose, then why not to set it to None? IMHO, t is misleading this way.

2021-04-01 09:28 UTC, vladkucherov approved these changes

2021-04-01 09:29 UTC, danprinz approved these changes

2021-04-01 09:30 UTC, merged